
markdown: rdiscount
pygments: true
permalink: /:title
relative_source: ../nrsite/
destination: ../nrsite/
# Settings for deploy rake task
# Username and repo of Github repo, e.g.
# https://github.com/USERNAME/REPO.git
# username defaults to ENV['GIT_NAME'] used by Travis
# repo defaults to USERNAME.github.io
# Branch defaults to "source" for USERNAME.github.io
# or "master" otherwise
username: NeuronRobotics
repo: NeuronRobotics.github.io
branch: source
permalink: /:categories/:title
gems: [jekyll-category-aware-prev-next]
exclude: ["vendor"]
